main: com.mullen.ethan.dungeonrunner.Main
name: DungeonRunner
version: 0.1
commands:
  dungeon:
  dungeonworld:
    aliases: [dw]  
libraries:
  - com.github.shynixn.structureblocklib:structureblocklib-bukkit-api:2.11.0
  - com.github.shynixn.structureblocklib:structureblocklib-bukkit-core:2.11.0
api-version: 1.19
depend: [NBTAPI, CustomMobs]